apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJuYW1hbnNoYXJtYTg4MjciLCJwYXNzd29yZCI6ImRja3JfcGF0X1NjM1l2WkJOM24tQnVTcWNXeTFWVHVmSVpjVSIsImF1dGgiOiJibUZ0WVc1emFHRnliV0U0T0RJM09tUmphM0pmY0dGMFgxTmpNMWwyV2tKT00yNHRRblZUY1dOWGVURldWSFZtU1ZwalZRPT0ifX19
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: default
type: kubernetes.io/dockerconfigjson